<?xml version="1.0"?>
<robot name="waver" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find waver_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find waver_description)/urdf/util.xacro" />
  <xacro:include filename="$(find waver_description)/urdf/waver.trans.xacro" />
  <xacro:include filename="$(find waver_description)/urdf/waver.gazebo.xacro" />

  <!-- ******************************* Links ******************************* -->

  <link name="base_footprint"></link>

  <link name="base_link">
    <inertial>
      <mass value="${mass_base}" />
      <origin xyz="${mass_center_base}" rpy="0 0 0" />
      <inertia ixx="8.590754" iyy="4.272701" izz="12.732361" ixy="-0.00783" iyz="-1.6e-05" ixz="-0.000187" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/base_link.stl" scale="${scale}" />
      </geometry>
      <xacro:dark_gray_material />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/base_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="top_shell_link">
    <inertial>
      <mass value="${mass_top}" />
      <origin xyz="${mass_center_top}" rpy="0 0 0" />
      <inertia ixx="23.275057" iyy="12.620651" izz="32.42524" ixy="-0.009322" iyz="0.010328" ixz="-0.015376" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/top_shell_link.stl" scale="${scale}" />
      </geometry>
      <xacro:dark_gray_material />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/top_shell_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="accessories_link">
    <inertial>
      <mass value="${mass_acces}" />
      <origin xyz="${mass_center_acces}" rpy="0 0 0" />
      <inertia ixx="0.015855" iyy="0.037389" izz="0.037412" ixy="0.00687" iyz="-0.007022" ixz="0.006879" />
    </inertial>
    <visual>
      <origin xyz="${position_acces}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/accessories_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_acces}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/accessories_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="accessories1_link">
    <inertial>
      <mass value="${mass_acces1}" />
      <origin xyz="${mass_center_acces1}" rpy="0 0 0" />
      <inertia ixx="0.008308" iyy="0.027844" izz="0.02786" ixy="0.000652" iyz="-0.002643" ixz="0.000591" />
    </inertial>
    <visual>
      <origin xyz="${position_acces1}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/accessories1_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_acces1}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/accessories1_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="board_link">
    <inertial>
      <mass value="${mass_board}" />
      <origin xyz="${mass_center_board}" rpy="0 0 0" />
      <inertia ixx="0.411139" iyy="0.524283" izz="0.881935" ixy="-0.000859" iyz="-0.000268" ixz="0.063417" />
    </inertial>
    <visual>
      <origin xyz="${position_board}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/board_link.stl" scale="${scale}" />
      </geometry>
      <xacro:dark_green_material />
    </visual>
    <collision>
      <origin xyz="${position_board}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/board_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="oled_screen_link">
    <inertial>
      <mass value="${mass_screen}" />
      <origin xyz="${mass_center_screen}" rpy="0 0 0" />
      <inertia ixx="0.002338" iyy="0.018383" izz="0.020177" ixy="-0.0" iyz="-3.9e-05" ixz="-0.0" />
    </inertial>
    <visual>
      <origin xyz="${position_screen}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/oled_screen_link.stl" scale="${scale}" />
      </geometry>
      <xacro:dark_blue_material />
    </visual>
    <collision>
      <origin xyz="${position_screen}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/oled_screen_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_back_left_link">
    <inertial>
      <mass value="${mass_wbl}" />
      <origin xyz="${mass_center_wbl}" rpy="0 0 0" />
      <inertia ixx="9.903047" iyy="6.209714" izz="6.209755" ixy="2e-06" iyz="1.5e-05" ixz="5e-06" />
    </inertial>
    <visual>
      <origin xyz="${position_wbl}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_back_left_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_wbl}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_back_left_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_front_left_link">
    <inertial>
      <mass value="${mass_wfl}" />
      <origin xyz="${mass_center_wfl}" rpy="0 0 0" />
      <inertia ixx="9.903064" iyy="6.20972" izz="6.20977" ixy="3e-06" iyz="9e-06" ixz="5e-06" />
    </inertial>
    <visual>
      <origin xyz="${position_wfl}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_front_left_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_wfl}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_front_left_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_front_right_link">
    <inertial>
      <mass value="${mass_wfr}" />
      <origin xyz="${mass_center_wfr}" rpy="0 0 0" />
      <inertia ixx="9.903034" iyy="6.2097" izz="6.209738" ixy="-7e-06" iyz="1e-05" ixz="6e-06" />
    </inertial>
    <visual>
      <origin xyz="${position_wfr}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_front_right_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_wfr}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_front_right_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <link name="wheel_back_right_link">
    <inertial>
      <mass value="${mass_wbr}" />
      <origin xyz="${mass_center_wbr}" rpy="0 0 0" />
      <inertia ixx="9.903051" iyy="6.209704" izz="6.209756" ixy="-7e-06" iyz="8e-06" ixz="5e-06" />
    </inertial>
    <visual>
      <origin xyz="${position_wbr}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_back_right_link.stl" scale="${scale}" />
      </geometry>
      <xacro:black_material />
    </visual>
    <collision>
      <origin xyz="${position_wbr}" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://waver_description/meshes/wheel_back_right_link.stl" scale="${scale}" />
      </geometry>
    </collision>
  </link>

  <!-- ******************************* Links ******************************* -->

  <joint
    name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 33.7e-3" rpy="0 0 0" />
    <parent link="base_footprint" />
    <child link="base_link" />
  </joint>

  <joint name="base_top_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="top_shell_link" />
  </joint>

  <joint name="top_acces_joint" type="fixed">
    <origin xyz="${mass_center_acces}" rpy="0 0 0" />
    <parent link="top_shell_link" />
    <child link="accessories_link" />
  </joint>

  <joint name="top_acces1_joint" type="fixed">
    <origin xyz="${mass_center_acces1}" rpy="0 0 0" />
    <parent link="top_shell_link" />
    <child link="accessories1_link" />
  </joint>

  <joint name="top_board_joint" type="fixed">
    <origin xyz="${mass_center_board}" rpy="0 0 0" />
    <parent link="top_shell_link" />
    <child link="board_link" />
  </joint>

  <joint name="top_screen_joint" type="fixed">
    <origin xyz="${mass_center_screen}" rpy="0 0 0" />
    <parent link="top_shell_link" />
    <child link="oled_screen_link" />
  </joint>

  <joint name="wheel_back_left_joint" type="continuous">
    <origin xyz="${mass_center_wbl}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_back_left_link" />
    <axis xyz="1 0 0" />
  </joint>

  <joint name="wheel_front_left_joint" type="continuous">
    <origin xyz="${mass_center_wfl}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_front_left_link" />
    <axis xyz="1 0 0" />
  </joint>

  <joint name="wheel_front_right_joint" type="continuous">
    <origin xyz="${mass_center_wfr}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_front_right_link" />
    <axis xyz="1 0 0" />
  </joint>

  <joint name="wheel_back_right_joint" type="continuous">
    <origin xyz="${mass_center_wbr}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_back_right_link" />
    <axis xyz="1 0 0" />
  </joint>

  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <robotNamespace></robotNamespace>
      <updateRate>100.0</updateRate>
      <leftFrontJoint>wheel_front_left_joint</leftFrontJoint>
      <rightFrontJoint>wheel_front_right_joint</rightFrontJoint>
      <leftRearJoint>wheel_back_left_joint</leftRearJoint>
      <rightRearJoint>wheel_back_right_joint</rightRearJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>10.0</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <publishWheelTF>true</publishWheelTF>
      <publishOdom>true</publishOdom>
      <publishWheelJointState>true</publishWheelJointState>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_yaw>0.01</covariance_yaw>
      <broadcastTF>true</broadcastTF>
    </plugin>
  </gazebo>
  

</robot>
